Repository NSLS2/nsls2api, pull requests merged in 2024-06, with the labels that each got.

#91 🫂 Add a real person to a proposal so we can test authenticating
  src/nsls2api/services/proposal_service.py
Labels: enhancement

#95 Fix issue with import httpx wrapper instance
  src/nsls2api/cli/auth.py
  src/nsls2api/infrastructure/app_setup.py
  src/nsls2api/infrastructure/mongodb_setup.py
  src/nsls2api/main.py
  src/nsls2api/services/bnlpeople_service.py
  src/nsls2api/services/helpers.py
  src/nsls2api/services/pass_service.py
  src/nsls2api/services/proposal_service.py
Labels: bug

#99 Fix API key generation
  src/nsls2api/api/v1/admin_api.py
  src/nsls2api/api/v1/beamline_api.py
  src/nsls2api/infrastructure/security.py
  src/nsls2api/models/apikeys.py
Labels: bug, enhancement
